name: Pull Request Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./TestAspnetCore.Web/
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./TestAspnetCore.Web/
    - name: Unit Test
      run: dotnet test --verbosity normal
      working-directory: ./TestAspnetCore.UnitTest
    - name: Integration Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./TestAspnetCore.IntegrationTest/
